# Generated by Django 4.2.6 on 2023-10-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='other_data',
            field=models.JSONField(),
        ),
    ]
